//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secondhand
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public int CategoryId { get; set; }
        public Nullable<int> Id { get; set; }
        public Nullable<int> subCategoryId { get; set; }
        public string ShortDescription { get; set; }
        public string img { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> publicationDate { get; set; }
        public Nullable<int> areaId { get; set; }
        public Nullable<int> ueserId { get; set; }
    
        public virtual areas areas { get; set; }
        public virtual areas areas1 { get; set; }
        public virtual subCategory subCategory { get; set; }
        public virtual subCategory subCategory1 { get; set; }
        public virtual users users { get; set; }
    }
}
