//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace secondhand
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rachelis_secondHand1Entities : DbContext
    {
        public rachelis_secondHand1Entities()
            : base("name=rachelis_secondHand1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<areas> areas { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<subCategory> subCategory { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
